version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password   # Cambia esta contraseña
      MYSQL_DATABASE: my_database          # Nombre de la base de datos inicial
      MYSQL_USER: user                     # Nombre de usuario
      MYSQL_PASSWORD: user_password        # Contraseña del usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
